### ISSUE TITLE
How didn't see about the kernel that fast?

### ISSUE THREAD

**Issue by nu1ee** [fenggui321/openwrt-ndpi-netfilter#1]
This is another
define KernelPackage/ipt-ndpi
  SUBMENU:=Netfilter Extensions
  TITLE:= nDPI net netfilter module
  DEPENDS:=+kmod-nf-conntrack +kmod-nf-conntrack-netlink +kmod-ipt-compat-xtables
  FILES:= \
	$(PKG_BUILD_DIR)/src/xt_ndpi.ko
  AUTOLOAD:=$(call AutoProbe,xt_ndpi)
endef
https://github.com/981213/lede_src/blob/master/package/my_package/ndpi-netfilter/Makefile

**Comment by fenggui321** [comment]
我猜你是中国人，没看懂你说的啥意思。

**Comment by nu1ee** [comment]
我说怎么每看到内核加载 这样可以用吗？

**Comment by fenggui321** [comment]
自动加载

**Comment by karldonitz** [comment]
编译到lede17的iptables部分出现了
config.status: error: cannot find input file: `Makefile.in'
请问大神要处理呀？

**Comment by fenggui321** [comment]
sorry,git 提交默认被过滤了。重新提交了。我在cc r43xx上，内核还是3.18不知道lede上能不能用。 @karldonitz
